import type { LocalTokenUsage, ProviderSnapshot } from "../../shared/index";
import {
  exactLocalTokens,
  formatLocalCalculatedAt,
  formatLocalDate,
  formatLocalShortDate,
  formatLocalTokens,
} from "../selectors";
import { HelpTrigger } from "./HelpTrigger";

export interface LocalUsageViewProps {
  providerId: ProviderSnapshot["providerId"];
  usage: LocalTokenUsage | undefined;
  activeHelp?: string;
  onActiveHelpChange(id?: string): void;
}

export const LocalUsageView = ({
  providerId,
  usage,
  activeHelp,
  onActiveHelpChange,
}: LocalUsageViewProps) => {
  if (!usage) return <span className="local-usage">this PC calculating</span>;
  if (usage.scannedFileCount === 0 && !usage.partial)
    return <span className="local-usage">this PC no local logs</span>;
  const id = (kind: string): string => `${providerId}-local-${kind}`;
  const observed = usage.observedFrom
    ? formatLocalShortDate(usage.observedFrom)
    : "unavailable";
  const help = (
    kind: string,
    label: string,
    value: string | undefined,
    description: string,
    tone?: "neutral" | "input" | "output" | "cache" | "partial",
  ) => (
    <HelpTrigger
      id={id(kind)}
      label={label}
      value={value}
      description={description}
      tone={tone}
      testId={id(kind)}
      activeHelp={activeHelp}
      onActiveHelpChange={onActiveHelpChange}
    />
  );
  return (
    <div className="local-usage" aria-label="Local tokens detail for this PC">
      <div className="local-usage-row">
        {help(
          "scope",
          "this PC",
          undefined,
          "Cumulative tokens from local logs remaining on this PC. Not account-wide or 5h/7d quota window values.",
        )}
        {help(
          "total",
          "total",
          formatLocalTokens(usage.totalTokens),
          `Unabbreviated total: ${exactLocalTokens(usage.totalTokens)} tokens. total = input + output (cache tokens not added twice). K=1,000, M=1,000,000, B=1,000,000,000.`,
        )}
        {help(
          "since",
          "since",
          observed,
          usage.observedFrom
            ? `Earliest event observed in local logs: ${formatLocalDate(usage.observedFrom)}. Not a quota reset or subscription start date. Calculated at: ${formatLocalCalculatedAt(usage.calculatedAt)}.`
            : `Earliest observed event date not provided. Calculated at: ${formatLocalCalculatedAt(usage.calculatedAt)}.`,
        )}
        {usage.partial
          ? help(
              "partial",
              "partial",
              String(usage.failedFileCount),
              `Verified partial total. ${exactLocalTokens(usage.failedFileCount)} file(s) had read or record processing issues. Will retry on next scan.`,
              "partial",
            )
          : null}
      </div>
      <div className="local-usage-row">
        {help(
          "input",
          "input",
          formatLocalTokens(usage.inputTokens),
          `Exact input: ${exactLocalTokens(usage.inputTokens)} tokens. Input tokens delivered to the model, including cache tokens.`,
          "input",
        )}
        {help(
          "output",
          "output",
          formatLocalTokens(usage.outputTokens),
          `Exact output: ${exactLocalTokens(usage.outputTokens)} tokens. Output tokens generated by the model.`,
          "output",
        )}
        {help(
          "cache-read",
          "cache read",
          usage.cacheReadTokens === undefined ? "--" : formatLocalTokens(usage.cacheReadTokens),
          usage.cacheReadTokens === undefined
            ? "Cache read value not provided."
            : `Exact cache read: ${exactLocalTokens(usage.cacheReadTokens)} tokens. Reused cache input tokens, already included in input.`,
          "cache",
        )}
        {help(
          "cache-write",
          "cache write",
          usage.cacheWriteTokens === undefined ? "--" : formatLocalTokens(usage.cacheWriteTokens),
          usage.cacheWriteTokens === undefined
            ? "Cache write value not provided."
            : `Exact cache write: ${exactLocalTokens(usage.cacheWriteTokens)} tokens. Newly written cache input tokens, already included in input.`,
          "cache",
        )}
      </div>
    </div>
  );
};
