use super::{format::format_token_count, theme::Palette};
use crate::core::types::LocalTokenUsage;
use gpui::{div, prelude::*, px, IntoElement, Rgba};
fn exact(value: u64) -> String {
    let digits = value.to_string();
    digits
        .chars()
        .enumerate()
        .fold(String::new(), |mut result, (index, ch)| {
            if index > 0 && (digits.len() - index) % 3 == 0 {
                result.push(',');
            }
            result.push(ch);
            result
        })
}
fn detail(
    id: &'static str,
    label: String,
    description: String,
    color: Rgba,
    p: Palette,
) -> impl IntoElement {
    div()
        .id(id)
        .text_color(color)
        .tooltip(move |_, cx| super::tooltip::tooltip(description.clone(), p, cx))
        .child(label)
}
pub fn render_usage(u: &LocalTokenUsage, p: Palette) -> impl IntoElement {
    let count = |v: Option<u64>| v.map(format_token_count).unwrap_or_else(|| "--".into());
    div()
        .flex()
        .flex_col()
        .text_color(p.muted)
        .when(u.scanned_file_count == 0 && !u.partial, |el| {
            el.child("this PC no local logs")
        })
        .when(u.scanned_file_count > 0 || u.partial, |el| {
            el.child(
                div()
                    .flex()
                    .flex_wrap()
                    .gap_x(px(7.))
                    .child(detail("scope","this PC".into(),"Cumulative tokens from local logs remaining on this PC. Not account-wide or 5h/7d quota window values.".into(),p.muted,p))
                    .child(detail("total",format!("total {}", format_token_count(u.total_tokens)),format!("Unabbreviated total: {} tokens. total = input + output (cache tokens not added twice). K=1,000, M=1,000,000, B=1,000,000,000.",exact(u.total_tokens)),p.muted,p))
                    .child(detail("since",format!(
                        "since {}",
                        u.observed_from
                            .map(|t| t
                                .with_timezone(&chrono::Local)
                                .format("%-m/%-d")
                                .to_string())
                            .unwrap_or_else(|| "unavailable".into())
                    ),format!("{}. Calculated at: {}.",u.observed_from.map(|t|format!("Earliest event observed in local logs: {}. Not a quota reset or subscription start date",t.with_timezone(&chrono::Local).format("%m/%d/%Y"))).unwrap_or_else(||"Earliest observed event date not provided".into()),u.calculated_at.with_timezone(&chrono::Local).format("%m/%d/%Y %-I:%M %p")),p.muted,p))
                    .children(u.partial.then(|| {
                        detail("partial",format!("partial {}",u.failed_file_count),format!("Verified partial total. {} file(s) had read or record processing issues. Will retry on next scan.",exact(u.failed_file_count)),p.medium,p)
                    })),
            )
            .child(
                div()
                    .flex()
                    .flex_wrap()
                    .gap_x(px(7.))
                    .child(detail("input",format!("input {}", format_token_count(u.input_tokens)),format!("Exact input: {} tokens. Input tokens delivered to the model, including cache tokens.",exact(u.input_tokens)),p.input,p))
                    .child(detail("output",format!("output {}", format_token_count(u.output_tokens)),format!("Exact output: {} tokens. Output tokens generated by the model.",exact(u.output_tokens)),p.output,p))
                    .child(detail("cache-read",format!("cache read {}", count(u.cache_read_tokens)),u.cache_read_tokens.map(|v|format!("Exact cache read: {} tokens. Reused cache input tokens, already included in input.",exact(v))).unwrap_or_else(||"Cache read value not provided.".into()),p.cache,p))
                    .child(detail("cache-write",format!("cache write {}", count(u.cache_write_tokens)),u.cache_write_tokens.map(|v|format!("Exact cache write: {} tokens. Newly written cache input tokens, already included in input.",exact(v))).unwrap_or_else(||"Cache write value not provided.".into()),p.cache,p)),
            )
        })
}
